### ISSUE TITLE
Acabar el ejercicio

### ISSUE THREAD

**Issue by nasivuela** [Adalab/dorcas-s3-evaluacion-intermedia-rqlromo#1]
Te dejo algunas pistas para que puedas mejorarlo:

- Iterar types en PokemonCard.
- Ya que cada pokemon tienen un id, utilizarlo para la propiedad key, en lugar del index
- Quitar espacios en atributos antes y después del `=` 
- Añadir carpeta components para que todo esté más organizadito.
- Mejorar la indentación.
- No descuidar la semántica de HTML (main, h1...)
- Animarte a hacer destructuring para no escribir tantas veces `this.props`
- Instalar la librería `prop-types` y usarla para comprobar el tipado js de las props.
- Acabar el css
- Eliminar archivos que no usamos (App.test.js, logo.svg...)

También te recomiendo publicar en Github Pages para practicar ;)

A por ello!

**Comment by rqlromo** [comment]
Gracias por las pistas @nasivuela 👍 
- He creado un map con una arrow function para no tener que bindear el this.
- Creo que he puesto bien lo del id, me lo podrías echar un vistazo y confirmar?
- Había puesto los espacios a proposito, pensaba que era mas correcto así XD, ya están fuera.
- Añadida carpeta componentes!
- Meti a ultima hora la lista y se me quedo la indentación patas arriba XD.
- Se me fue un poco con los nervios si...
- Ya he hecho destructuring donde no lo había hecho.
- Me molan las props (icono corazones en los ojos).
-  Ya le he dado unos estilillos, tampoco lo he dejado perfect pero react no espera.
- El archivo App.test.js para que sirve? He limpiado lo que no utilizaba

Publicarlo en Github Pages lo hare el finde

Dudas: 
      - Es correcto que haya prescindido de App y haya puesto el titulo de "Mi lista de Pokemons" en la PokemonList??

Muchas gracias por tus pistas nas!!

**Comment by rqlromo** [comment]
Ya esta publicado en Github Pages ;)

**Comment by nasivuela** [comment]
Buen trabajo!!!
El archivo App.test.js sirve para testear nuestro código, más adelante veremos como hacer esto, pero de momento como nolo usamos mejor quitarlo ;)
